linear_regression: prime
	g++ linear_regression.cpp -o linear_regression
	./linear_regression
prime: sum_of_digits
	g++ prime.cpp -o prime
	./prime
sum_of_digits: ex4.5
	g++ sum_of_digits.cpp -o sum_of_digits
	./sum_of_digits
ex4.5:
	g++ ex4.5.cpp -o ex4.5
	./ex4.5