nutrition: inflation
	g++ nutrition.cpp -o nutrition
	./nutrition
inflation: ex4.28
	g++ inflation.cpp -o inflation
	./inflation
ex4.28: ex3.23
	g++ ex4.28.cpp -o ex4.28
	./ex4.28
ex3.23: ex3.17
	g++ ex3.23.cpp -o ex3.23
	./ex3.23
ex3.17:
	g++ ex3.17.cpp -o ex3.17
	./ex3.17